version: '3'

services:
   make:
      image: usdaarsnwrc/basin_setup:{{cookiecutter.basin_setup_version}}
      volumes:
        - ./:/data
        - ~/Downloads:/Downloads
      entrypoint: make

   cmd:
      image: usdaarsnwrc/basin_setup:{{cookiecutter.basin_setup_version}}
      volumes:
        - ./:/data
      entrypoint: /bin/bash
